### ISSUE TITLE
Where did the references go?! :D

### ISSUE THREAD

**Issue by dionyziz** [decrypto-org/rupture#307]

**Comment by dimkarakostas** [comment]
Do you mean the citations? [Here](https://github.com/dionyziz/rupture/blob/develop/etc/theory/compression_security.tex#L96) they are. Have you tried recompiling the latex?

**Comment by dionyziz** [comment]
I don't see them in the rendered PDF – do you?

**Comment by dimkarakostas** [comment]
Yes. Try removing the aux file and recompiling the latex, or else check with `bibtex compression_security.aux`.

**Comment by dimkarakostas** [comment]
try the following (deterministic process :P ):

- remove `compression_security.aux`
- compile `compression_security.tex`
- check with `bibtex compression_security.aux` to see no errors exist
- recompile `compression_security.tex`, should add the references section
- if citations are broken recompile
